// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/athena/protobuf/message.proto

package com.athena.protobuf;

public final class MessageEntity {
  private MessageEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.athena.protobuf.messageType}
   */
  public enum messageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TO_SINGLE = 1;</code>
     */
    TO_SINGLE(1),
    /**
     * <code>TO_GROUP = 2;</code>
     */
    TO_GROUP(2),
    ;

    /**
     * <code>TO_SINGLE = 1;</code>
     */
    public static final int TO_SINGLE_VALUE = 1;
    /**
     * <code>TO_GROUP = 2;</code>
     */
    public static final int TO_GROUP_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static messageType valueOf(int value) {
      return forNumber(value);
    }

    public static messageType forNumber(int value) {
      switch (value) {
        case 1: return TO_SINGLE;
        case 2: return TO_GROUP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<messageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        messageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<messageType>() {
            public messageType findValueByNumber(int number) {
              return messageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.athena.protobuf.MessageEntity.getDescriptor().getEnumTypes().get(0);
    }

    private static final messageType[] VALUES = values();

    public static messageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private messageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.athena.protobuf.messageType)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.athena.protobuf.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 messageId = 1;</code>
     */
    boolean hasMessageId();
    /**
     * <code>required int64 messageId = 1;</code>
     */
    long getMessageId();

    /**
     * <code>required int64 senderId = 2;</code>
     */
    boolean hasSenderId();
    /**
     * <code>required int64 senderId = 2;</code>
     */
    long getSenderId();

    /**
     * <code>optional int64 recipientId = 3;</code>
     */
    boolean hasRecipientId();
    /**
     * <code>optional int64 recipientId = 3;</code>
     */
    long getRecipientId();

    /**
     * <code>optional string header = 4;</code>
     */
    boolean hasHeader();
    /**
     * <code>optional string header = 4;</code>
     */
    java.lang.String getHeader();
    /**
     * <code>optional string header = 4;</code>
     */
    com.google.protobuf.ByteString
        getHeaderBytes();

    /**
     * <code>required string body = 5;</code>
     */
    boolean hasBody();
    /**
     * <code>required string body = 5;</code>
     */
    java.lang.String getBody();
    /**
     * <code>required string body = 5;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>required .com.athena.protobuf.messageType type = 6;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.athena.protobuf.messageType type = 6;</code>
     */
    com.athena.protobuf.MessageEntity.messageType getType();

    /**
     * <code>optional int32 groupId = 7;</code>
     */
    boolean hasGroupId();
    /**
     * <code>optional int32 groupId = 7;</code>
     */
    int getGroupId();
  }
  /**
   * Protobuf type {@code com.athena.protobuf.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.athena.protobuf.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      messageId_ = 0L;
      senderId_ = 0L;
      recipientId_ = 0L;
      header_ = "";
      body_ = "";
      type_ = 1;
      groupId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              messageId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              senderId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              recipientId_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              header_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              body_ = bs;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.athena.protobuf.MessageEntity.messageType value = com.athena.protobuf.MessageEntity.messageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                type_ = rawValue;
              }
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              groupId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.athena.protobuf.MessageEntity.internal_static_com_athena_protobuf_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.athena.protobuf.MessageEntity.internal_static_com_athena_protobuf_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.athena.protobuf.MessageEntity.Message.class, com.athena.protobuf.MessageEntity.Message.Builder.class);
    }

    private int bitField0_;
    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private long messageId_;
    /**
     * <code>required int64 messageId = 1;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 messageId = 1;</code>
     */
    public long getMessageId() {
      return messageId_;
    }

    public static final int SENDERID_FIELD_NUMBER = 2;
    private long senderId_;
    /**
     * <code>required int64 senderId = 2;</code>
     */
    public boolean hasSenderId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 senderId = 2;</code>
     */
    public long getSenderId() {
      return senderId_;
    }

    public static final int RECIPIENTID_FIELD_NUMBER = 3;
    private long recipientId_;
    /**
     * <code>optional int64 recipientId = 3;</code>
     */
    public boolean hasRecipientId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 recipientId = 3;</code>
     */
    public long getRecipientId() {
      return recipientId_;
    }

    public static final int HEADER_FIELD_NUMBER = 4;
    private volatile java.lang.Object header_;
    /**
     * <code>optional string header = 4;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string header = 4;</code>
     */
    public java.lang.String getHeader() {
      java.lang.Object ref = header_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          header_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string header = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHeaderBytes() {
      java.lang.Object ref = header_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        header_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 5;
    private volatile java.lang.Object body_;
    /**
     * <code>required string body = 5;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string body = 5;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string body = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private int type_;
    /**
     * <code>required .com.athena.protobuf.messageType type = 6;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required .com.athena.protobuf.messageType type = 6;</code>
     */
    public com.athena.protobuf.MessageEntity.messageType getType() {
      com.athena.protobuf.MessageEntity.messageType result = com.athena.protobuf.MessageEntity.messageType.valueOf(type_);
      return result == null ? com.athena.protobuf.MessageEntity.messageType.TO_SINGLE : result;
    }

    public static final int GROUPID_FIELD_NUMBER = 7;
    private int groupId_;
    /**
     * <code>optional int32 groupId = 7;</code>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 groupId = 7;</code>
     */
    public int getGroupId() {
      return groupId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMessageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSenderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, senderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, recipientId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, header_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, body_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, type_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, groupId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, messageId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, senderId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, recipientId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, header_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, body_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, type_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, groupId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.athena.protobuf.MessageEntity.Message)) {
        return super.equals(obj);
      }
      com.athena.protobuf.MessageEntity.Message other = (com.athena.protobuf.MessageEntity.Message) obj;

      boolean result = true;
      result = result && (hasMessageId() == other.hasMessageId());
      if (hasMessageId()) {
        result = result && (getMessageId()
            == other.getMessageId());
      }
      result = result && (hasSenderId() == other.hasSenderId());
      if (hasSenderId()) {
        result = result && (getSenderId()
            == other.getSenderId());
      }
      result = result && (hasRecipientId() == other.hasRecipientId());
      if (hasRecipientId()) {
        result = result && (getRecipientId()
            == other.getRecipientId());
      }
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasGroupId() == other.hasGroupId());
      if (hasGroupId()) {
        result = result && (getGroupId()
            == other.getGroupId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessageId()) {
        hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMessageId());
      }
      if (hasSenderId()) {
        hash = (37 * hash) + SENDERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSenderId());
      }
      if (hasRecipientId()) {
        hash = (37 * hash) + RECIPIENTID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRecipientId());
      }
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasGroupId()) {
        hash = (37 * hash) + GROUPID_FIELD_NUMBER;
        hash = (53 * hash) + getGroupId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.athena.protobuf.MessageEntity.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.athena.protobuf.MessageEntity.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.athena.protobuf.MessageEntity.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.athena.protobuf.MessageEntity.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.athena.protobuf.MessageEntity.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.athena.protobuf.MessageEntity.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.athena.protobuf.MessageEntity.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.athena.protobuf.MessageEntity.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.athena.protobuf.MessageEntity.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.athena.protobuf.MessageEntity.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.athena.protobuf.MessageEntity.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.athena.protobuf.MessageEntity.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.athena.protobuf.MessageEntity.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.athena.protobuf.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.athena.protobuf.Message)
        com.athena.protobuf.MessageEntity.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.athena.protobuf.MessageEntity.internal_static_com_athena_protobuf_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.athena.protobuf.MessageEntity.internal_static_com_athena_protobuf_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.athena.protobuf.MessageEntity.Message.class, com.athena.protobuf.MessageEntity.Message.Builder.class);
      }

      // Construct using com.athena.protobuf.MessageEntity.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        messageId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        senderId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        recipientId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        header_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000020);
        groupId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.athena.protobuf.MessageEntity.internal_static_com_athena_protobuf_Message_descriptor;
      }

      public com.athena.protobuf.MessageEntity.Message getDefaultInstanceForType() {
        return com.athena.protobuf.MessageEntity.Message.getDefaultInstance();
      }

      public com.athena.protobuf.MessageEntity.Message build() {
        com.athena.protobuf.MessageEntity.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.athena.protobuf.MessageEntity.Message buildPartial() {
        com.athena.protobuf.MessageEntity.Message result = new com.athena.protobuf.MessageEntity.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.senderId_ = senderId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.recipientId_ = recipientId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.header_ = header_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.groupId_ = groupId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.athena.protobuf.MessageEntity.Message) {
          return mergeFrom((com.athena.protobuf.MessageEntity.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.athena.protobuf.MessageEntity.Message other) {
        if (other == com.athena.protobuf.MessageEntity.Message.getDefaultInstance()) return this;
        if (other.hasMessageId()) {
          setMessageId(other.getMessageId());
        }
        if (other.hasSenderId()) {
          setSenderId(other.getSenderId());
        }
        if (other.hasRecipientId()) {
          setRecipientId(other.getRecipientId());
        }
        if (other.hasHeader()) {
          bitField0_ |= 0x00000008;
          header_ = other.header_;
          onChanged();
        }
        if (other.hasBody()) {
          bitField0_ |= 0x00000010;
          body_ = other.body_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasGroupId()) {
          setGroupId(other.getGroupId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageId()) {
          return false;
        }
        if (!hasSenderId()) {
          return false;
        }
        if (!hasBody()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.athena.protobuf.MessageEntity.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.athena.protobuf.MessageEntity.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long messageId_ ;
      /**
       * <code>required int64 messageId = 1;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 messageId = 1;</code>
       */
      public long getMessageId() {
        return messageId_;
      }
      /**
       * <code>required int64 messageId = 1;</code>
       */
      public Builder setMessageId(long value) {
        bitField0_ |= 0x00000001;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 messageId = 1;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = 0L;
        onChanged();
        return this;
      }

      private long senderId_ ;
      /**
       * <code>required int64 senderId = 2;</code>
       */
      public boolean hasSenderId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 senderId = 2;</code>
       */
      public long getSenderId() {
        return senderId_;
      }
      /**
       * <code>required int64 senderId = 2;</code>
       */
      public Builder setSenderId(long value) {
        bitField0_ |= 0x00000002;
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 senderId = 2;</code>
       */
      public Builder clearSenderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        senderId_ = 0L;
        onChanged();
        return this;
      }

      private long recipientId_ ;
      /**
       * <code>optional int64 recipientId = 3;</code>
       */
      public boolean hasRecipientId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 recipientId = 3;</code>
       */
      public long getRecipientId() {
        return recipientId_;
      }
      /**
       * <code>optional int64 recipientId = 3;</code>
       */
      public Builder setRecipientId(long value) {
        bitField0_ |= 0x00000004;
        recipientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 recipientId = 3;</code>
       */
      public Builder clearRecipientId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        recipientId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object header_ = "";
      /**
       * <code>optional string header = 4;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string header = 4;</code>
       */
      public java.lang.String getHeader() {
        java.lang.Object ref = header_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            header_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string header = 4;</code>
       */
      public com.google.protobuf.ByteString
          getHeaderBytes() {
        java.lang.Object ref = header_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          header_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string header = 4;</code>
       */
      public Builder setHeader(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        header_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string header = 4;</code>
       */
      public Builder clearHeader() {
        bitField0_ = (bitField0_ & ~0x00000008);
        header_ = getDefaultInstance().getHeader();
        onChanged();
        return this;
      }
      /**
       * <code>optional string header = 4;</code>
       */
      public Builder setHeaderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        header_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object body_ = "";
      /**
       * <code>required string body = 5;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string body = 5;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            body_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string body = 5;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string body = 5;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string body = 5;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000010);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>required string body = 5;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        body_ = value;
        onChanged();
        return this;
      }

      private int type_ = 1;
      /**
       * <code>required .com.athena.protobuf.messageType type = 6;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required .com.athena.protobuf.messageType type = 6;</code>
       */
      public com.athena.protobuf.MessageEntity.messageType getType() {
        com.athena.protobuf.MessageEntity.messageType result = com.athena.protobuf.MessageEntity.messageType.valueOf(type_);
        return result == null ? com.athena.protobuf.MessageEntity.messageType.TO_SINGLE : result;
      }
      /**
       * <code>required .com.athena.protobuf.messageType type = 6;</code>
       */
      public Builder setType(com.athena.protobuf.MessageEntity.messageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.athena.protobuf.messageType type = 6;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 1;
        onChanged();
        return this;
      }

      private int groupId_ ;
      /**
       * <code>optional int32 groupId = 7;</code>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 groupId = 7;</code>
       */
      public int getGroupId() {
        return groupId_;
      }
      /**
       * <code>optional int32 groupId = 7;</code>
       */
      public Builder setGroupId(int value) {
        bitField0_ |= 0x00000040;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 groupId = 7;</code>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        groupId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.athena.protobuf.Message)
    }

    // @@protoc_insertion_point(class_scope:com.athena.protobuf.Message)
    private static final com.athena.protobuf.MessageEntity.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.athena.protobuf.MessageEntity.Message();
    }

    public static com.athena.protobuf.MessageEntity.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public com.athena.protobuf.MessageEntity.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_athena_protobuf_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_athena_protobuf_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n/src/main/java/com/athena/protobuf/mess" +
      "age.proto\022\023com.athena.protobuf\"\242\001\n\007Messa" +
      "ge\022\021\n\tmessageId\030\001 \002(\003\022\020\n\010senderId\030\002 \002(\003\022" +
      "\023\n\013recipientId\030\003 \001(\003\022\016\n\006header\030\004 \001(\t\022\014\n\004" +
      "body\030\005 \002(\t\022.\n\004type\030\006 \002(\0162 .com.athena.pr" +
      "otobuf.messageType\022\017\n\007groupId\030\007 \001(\005**\n\013m" +
      "essageType\022\r\n\tTO_SINGLE\020\001\022\014\n\010TO_GROUP\020\002B" +
      "&\n\023com.athena.protobufB\rMessageEntityH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_athena_protobuf_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_athena_protobuf_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_athena_protobuf_Message_descriptor,
        new java.lang.String[] { "MessageId", "SenderId", "RecipientId", "Header", "Body", "Type", "GroupId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
