// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request.proto

package com.athena.protobuf;

public final class RequestEntity {
  private RequestEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.athena.protobuf.PacketType}
   */
  public enum PacketType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HANDSHAKE = 1;</code>
     */
    HANDSHAKE(1),
    /**
     * <code>SUBSCRIBE = 2;</code>
     */
    SUBSCRIBE(2),
    /**
     * <code>ACK = 3;</code>
     */
    ACK(3),
    /**
     * <code>PUB = 4;</code>
     */
    PUB(4),
    ;

    /**
     * <code>HANDSHAKE = 1;</code>
     */
    public static final int HANDSHAKE_VALUE = 1;
    /**
     * <code>SUBSCRIBE = 2;</code>
     */
    public static final int SUBSCRIBE_VALUE = 2;
    /**
     * <code>ACK = 3;</code>
     */
    public static final int ACK_VALUE = 3;
    /**
     * <code>PUB = 4;</code>
     */
    public static final int PUB_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PacketType valueOf(int value) {
      return forNumber(value);
    }

    public static PacketType forNumber(int value) {
      switch (value) {
        case 1: return HANDSHAKE;
        case 2: return SUBSCRIBE;
        case 3: return ACK;
        case 4: return PUB;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PacketType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PacketType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PacketType>() {
            public PacketType findValueByNumber(int number) {
              return PacketType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.athena.protobuf.RequestEntity.getDescriptor().getEnumTypes().get(0);
    }

    private static final PacketType[] VALUES = values();

    public static PacketType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PacketType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.athena.protobuf.PacketType)
  }

  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.athena.protobuf.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.athena.protobuf.PacketType requestType = 1;</code>
     */
    boolean hasRequestType();
    /**
     * <code>required .com.athena.protobuf.PacketType requestType = 1;</code>
     */
    com.athena.protobuf.RequestEntity.PacketType getRequestType();

    /**
     * <code>optional int32 groupId = 2;</code>
     */
    boolean hasGroupId();
    /**
     * <code>optional int32 groupId = 2;</code>
     */
    int getGroupId();

    /**
     * <code>required int64 clientId = 3;</code>
     */
    boolean hasClientId();
    /**
     * <code>required int64 clientId = 3;</code>
     */
    long getClientId();

    /**
     * <code>required string authToken = 4;</code>
     */
    boolean hasAuthToken();
    /**
     * <code>required string authToken = 4;</code>
     */
    java.lang.String getAuthToken();
    /**
     * <code>required string authToken = 4;</code>
     */
    com.google.protobuf.ByteString
        getAuthTokenBytes();

    /**
     * <code>optional .com.athena.protobuf.Message message = 5;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional .com.athena.protobuf.Message message = 5;</code>
     */
    com.athena.protobuf.MessageEntity.Message getMessage();
    /**
     * <code>optional .com.athena.protobuf.Message message = 5;</code>
     */
    com.athena.protobuf.MessageEntity.MessageOrBuilder getMessageOrBuilder();
  }
  /**
   * Protobuf type {@code com.athena.protobuf.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.athena.protobuf.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      requestType_ = 1;
      groupId_ = 0;
      clientId_ = 0L;
      authToken_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.athena.protobuf.RequestEntity.PacketType value = com.athena.protobuf.RequestEntity.PacketType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                requestType_ = rawValue;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              groupId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              clientId_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              authToken_ = bs;
              break;
            }
            case 42: {
              com.athena.protobuf.MessageEntity.Message.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = message_.toBuilder();
              }
              message_ = input.readMessage(com.athena.protobuf.MessageEntity.Message.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(message_);
                message_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.athena.protobuf.RequestEntity.internal_static_com_athena_protobuf_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.athena.protobuf.RequestEntity.internal_static_com_athena_protobuf_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.athena.protobuf.RequestEntity.Request.class, com.athena.protobuf.RequestEntity.Request.Builder.class);
    }

    private int bitField0_;
    public static final int REQUESTTYPE_FIELD_NUMBER = 1;
    private int requestType_;
    /**
     * <code>required .com.athena.protobuf.PacketType requestType = 1;</code>
     */
    public boolean hasRequestType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.athena.protobuf.PacketType requestType = 1;</code>
     */
    public com.athena.protobuf.RequestEntity.PacketType getRequestType() {
      com.athena.protobuf.RequestEntity.PacketType result = com.athena.protobuf.RequestEntity.PacketType.valueOf(requestType_);
      return result == null ? com.athena.protobuf.RequestEntity.PacketType.HANDSHAKE : result;
    }

    public static final int GROUPID_FIELD_NUMBER = 2;
    private int groupId_;
    /**
     * <code>optional int32 groupId = 2;</code>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 groupId = 2;</code>
     */
    public int getGroupId() {
      return groupId_;
    }

    public static final int CLIENTID_FIELD_NUMBER = 3;
    private long clientId_;
    /**
     * <code>required int64 clientId = 3;</code>
     */
    public boolean hasClientId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 clientId = 3;</code>
     */
    public long getClientId() {
      return clientId_;
    }

    public static final int AUTHTOKEN_FIELD_NUMBER = 4;
    private volatile java.lang.Object authToken_;
    /**
     * <code>required string authToken = 4;</code>
     */
    public boolean hasAuthToken() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string authToken = 4;</code>
     */
    public java.lang.String getAuthToken() {
      java.lang.Object ref = authToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          authToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string authToken = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAuthTokenBytes() {
      java.lang.Object ref = authToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 5;
    private com.athena.protobuf.MessageEntity.Message message_;
    /**
     * <code>optional .com.athena.protobuf.Message message = 5;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .com.athena.protobuf.Message message = 5;</code>
     */
    public com.athena.protobuf.MessageEntity.Message getMessage() {
      return message_ == null ? com.athena.protobuf.MessageEntity.Message.getDefaultInstance() : message_;
    }
    /**
     * <code>optional .com.athena.protobuf.Message message = 5;</code>
     */
    public com.athena.protobuf.MessageEntity.MessageOrBuilder getMessageOrBuilder() {
      return message_ == null ? com.athena.protobuf.MessageEntity.Message.getDefaultInstance() : message_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRequestType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasClientId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAuthToken()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasMessage()) {
        if (!getMessage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, requestType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, groupId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, clientId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, authToken_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, getMessage());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, requestType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, groupId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, clientId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, authToken_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.athena.protobuf.RequestEntity.Request)) {
        return super.equals(obj);
      }
      com.athena.protobuf.RequestEntity.Request other = (com.athena.protobuf.RequestEntity.Request) obj;

      boolean result = true;
      result = result && (hasRequestType() == other.hasRequestType());
      if (hasRequestType()) {
        result = result && requestType_ == other.requestType_;
      }
      result = result && (hasGroupId() == other.hasGroupId());
      if (hasGroupId()) {
        result = result && (getGroupId()
            == other.getGroupId());
      }
      result = result && (hasClientId() == other.hasClientId());
      if (hasClientId()) {
        result = result && (getClientId()
            == other.getClientId());
      }
      result = result && (hasAuthToken() == other.hasAuthToken());
      if (hasAuthToken()) {
        result = result && getAuthToken()
            .equals(other.getAuthToken());
      }
      result = result && (hasMessage() == other.hasMessage());
      if (hasMessage()) {
        result = result && getMessage()
            .equals(other.getMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequestType()) {
        hash = (37 * hash) + REQUESTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + requestType_;
      }
      if (hasGroupId()) {
        hash = (37 * hash) + GROUPID_FIELD_NUMBER;
        hash = (53 * hash) + getGroupId();
      }
      if (hasClientId()) {
        hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getClientId());
      }
      if (hasAuthToken()) {
        hash = (37 * hash) + AUTHTOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getAuthToken().hashCode();
      }
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.athena.protobuf.RequestEntity.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.athena.protobuf.RequestEntity.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.athena.protobuf.RequestEntity.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.athena.protobuf.RequestEntity.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.athena.protobuf.RequestEntity.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.athena.protobuf.RequestEntity.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.athena.protobuf.RequestEntity.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.athena.protobuf.RequestEntity.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.athena.protobuf.RequestEntity.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.athena.protobuf.RequestEntity.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.athena.protobuf.RequestEntity.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.athena.protobuf.RequestEntity.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.athena.protobuf.RequestEntity.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.athena.protobuf.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.athena.protobuf.Request)
        com.athena.protobuf.RequestEntity.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.athena.protobuf.RequestEntity.internal_static_com_athena_protobuf_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.athena.protobuf.RequestEntity.internal_static_com_athena_protobuf_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.athena.protobuf.RequestEntity.Request.class, com.athena.protobuf.RequestEntity.Request.Builder.class);
      }

      // Construct using com.athena.protobuf.RequestEntity.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        requestType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        groupId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        clientId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        authToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (messageBuilder_ == null) {
          message_ = null;
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.athena.protobuf.RequestEntity.internal_static_com_athena_protobuf_Request_descriptor;
      }

      public com.athena.protobuf.RequestEntity.Request getDefaultInstanceForType() {
        return com.athena.protobuf.RequestEntity.Request.getDefaultInstance();
      }

      public com.athena.protobuf.RequestEntity.Request build() {
        com.athena.protobuf.RequestEntity.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.athena.protobuf.RequestEntity.Request buildPartial() {
        com.athena.protobuf.RequestEntity.Request result = new com.athena.protobuf.RequestEntity.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestType_ = requestType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.groupId_ = groupId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clientId_ = clientId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.authToken_ = authToken_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (messageBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.athena.protobuf.RequestEntity.Request) {
          return mergeFrom((com.athena.protobuf.RequestEntity.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.athena.protobuf.RequestEntity.Request other) {
        if (other == com.athena.protobuf.RequestEntity.Request.getDefaultInstance()) return this;
        if (other.hasRequestType()) {
          setRequestType(other.getRequestType());
        }
        if (other.hasGroupId()) {
          setGroupId(other.getGroupId());
        }
        if (other.hasClientId()) {
          setClientId(other.getClientId());
        }
        if (other.hasAuthToken()) {
          bitField0_ |= 0x00000008;
          authToken_ = other.authToken_;
          onChanged();
        }
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequestType()) {
          return false;
        }
        if (!hasClientId()) {
          return false;
        }
        if (!hasAuthToken()) {
          return false;
        }
        if (hasMessage()) {
          if (!getMessage().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.athena.protobuf.RequestEntity.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.athena.protobuf.RequestEntity.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int requestType_ = 1;
      /**
       * <code>required .com.athena.protobuf.PacketType requestType = 1;</code>
       */
      public boolean hasRequestType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.athena.protobuf.PacketType requestType = 1;</code>
       */
      public com.athena.protobuf.RequestEntity.PacketType getRequestType() {
        com.athena.protobuf.RequestEntity.PacketType result = com.athena.protobuf.RequestEntity.PacketType.valueOf(requestType_);
        return result == null ? com.athena.protobuf.RequestEntity.PacketType.HANDSHAKE : result;
      }
      /**
       * <code>required .com.athena.protobuf.PacketType requestType = 1;</code>
       */
      public Builder setRequestType(com.athena.protobuf.RequestEntity.PacketType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        requestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.athena.protobuf.PacketType requestType = 1;</code>
       */
      public Builder clearRequestType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestType_ = 1;
        onChanged();
        return this;
      }

      private int groupId_ ;
      /**
       * <code>optional int32 groupId = 2;</code>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 groupId = 2;</code>
       */
      public int getGroupId() {
        return groupId_;
      }
      /**
       * <code>optional int32 groupId = 2;</code>
       */
      public Builder setGroupId(int value) {
        bitField0_ |= 0x00000002;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 groupId = 2;</code>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        groupId_ = 0;
        onChanged();
        return this;
      }

      private long clientId_ ;
      /**
       * <code>required int64 clientId = 3;</code>
       */
      public boolean hasClientId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 clientId = 3;</code>
       */
      public long getClientId() {
        return clientId_;
      }
      /**
       * <code>required int64 clientId = 3;</code>
       */
      public Builder setClientId(long value) {
        bitField0_ |= 0x00000004;
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 clientId = 3;</code>
       */
      public Builder clearClientId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clientId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object authToken_ = "";
      /**
       * <code>required string authToken = 4;</code>
       */
      public boolean hasAuthToken() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string authToken = 4;</code>
       */
      public java.lang.String getAuthToken() {
        java.lang.Object ref = authToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            authToken_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string authToken = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAuthTokenBytes() {
        java.lang.Object ref = authToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string authToken = 4;</code>
       */
      public Builder setAuthToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        authToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string authToken = 4;</code>
       */
      public Builder clearAuthToken() {
        bitField0_ = (bitField0_ & ~0x00000008);
        authToken_ = getDefaultInstance().getAuthToken();
        onChanged();
        return this;
      }
      /**
       * <code>required string authToken = 4;</code>
       */
      public Builder setAuthTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        authToken_ = value;
        onChanged();
        return this;
      }

      private com.athena.protobuf.MessageEntity.Message message_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.athena.protobuf.MessageEntity.Message, com.athena.protobuf.MessageEntity.Message.Builder, com.athena.protobuf.MessageEntity.MessageOrBuilder> messageBuilder_;
      /**
       * <code>optional .com.athena.protobuf.Message message = 5;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.athena.protobuf.Message message = 5;</code>
       */
      public com.athena.protobuf.MessageEntity.Message getMessage() {
        if (messageBuilder_ == null) {
          return message_ == null ? com.athena.protobuf.MessageEntity.Message.getDefaultInstance() : message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.athena.protobuf.Message message = 5;</code>
       */
      public Builder setMessage(com.athena.protobuf.MessageEntity.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.athena.protobuf.Message message = 5;</code>
       */
      public Builder setMessage(
          com.athena.protobuf.MessageEntity.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.athena.protobuf.Message message = 5;</code>
       */
      public Builder mergeMessage(com.athena.protobuf.MessageEntity.Message value) {
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              message_ != null &&
              message_ != com.athena.protobuf.MessageEntity.Message.getDefaultInstance()) {
            message_ =
              com.athena.protobuf.MessageEntity.Message.newBuilder(message_).mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          messageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .com.athena.protobuf.Message message = 5;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = null;
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .com.athena.protobuf.Message message = 5;</code>
       */
      public com.athena.protobuf.MessageEntity.Message.Builder getMessageBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.athena.protobuf.Message message = 5;</code>
       */
      public com.athena.protobuf.MessageEntity.MessageOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_ == null ?
              com.athena.protobuf.MessageEntity.Message.getDefaultInstance() : message_;
        }
      }
      /**
       * <code>optional .com.athena.protobuf.Message message = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.athena.protobuf.MessageEntity.Message, com.athena.protobuf.MessageEntity.Message.Builder, com.athena.protobuf.MessageEntity.MessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.athena.protobuf.MessageEntity.Message, com.athena.protobuf.MessageEntity.Message.Builder, com.athena.protobuf.MessageEntity.MessageOrBuilder>(
                  getMessage(),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.athena.protobuf.Request)
    }

    // @@protoc_insertion_point(class_scope:com.athena.protobuf.Request)
    private static final com.athena.protobuf.RequestEntity.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.athena.protobuf.RequestEntity.Request();
    }

    public static com.athena.protobuf.RequestEntity.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.athena.protobuf.RequestEntity.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_athena_protobuf_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_athena_protobuf_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rrequest.proto\022\023com.athena.protobuf\032\rme" +
      "ssage.proto\"\244\001\n\007Request\0224\n\013requestType\030\001" +
      " \002(\0162\037.com.athena.protobuf.PacketType\022\017\n" +
      "\007groupId\030\002 \001(\005\022\020\n\010clientId\030\003 \002(\003\022\021\n\tauth" +
      "Token\030\004 \002(\t\022-\n\007message\030\005 \001(\0132\034.com.athen" +
      "a.protobuf.Message*<\n\nPacketType\022\r\n\tHAND" +
      "SHAKE\020\001\022\r\n\tSUBSCRIBE\020\002\022\007\n\003ACK\020\003\022\007\n\003PUB\020\004" +
      "B&\n\023com.athena.protobufB\rRequestEntityH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.athena.protobuf.MessageEntity.getDescriptor(),
        }, assigner);
    internal_static_com_athena_protobuf_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_athena_protobuf_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_athena_protobuf_Request_descriptor,
        new java.lang.String[] { "RequestType", "GroupId", "ClientId", "AuthToken", "Message", });
    com.athena.protobuf.MessageEntity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
